name: CI

on:
  push:
    branches:
      - dev
      - master
    tags:
  pull_request:
  release:

jobs:
  vet:
    name: Vetting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Checkout
        uses: actions/checkout@v2

      - name: Dependencies
        run: |
          go mod tidy
          docker pull trufflesuite/ganache-cli

      - name: Start Ganache
        run: |
          docker run --name=ganache -d --rm -p 8545:8545 trufflesuite/ganache-cli -g 10 -e 1000 -m "pistol kiwi shrug future ozone ostrich match remove crucial oblige cream critic"
          sleep 5
        
      - name: Unit Tests
        run: go test -timeout 120s -v ./...

      - name: Unit Race Tests
        run: go test -timeout 120s -v -race ./...

      - name: Stop Ganache
        run: docker stop ganache
